[Fix-736] Handle arrow direction date tooltip
hasadna/anyway-newsflash-infographics pull request #738
Opened 2021-08-07 07:08 UTC by MashaPav

Handle issue https://github.com/hasadna/anyway-newsflash-infographics/issues/736

2021-08-09 16:40 UTC, SejoB requested changes

2021-08-09 16:40 UTC, SejoB commented on src/components/atoms/TooltipMarker.tsx
> +      <div className={classes.content} style={{order: i18n.language === 'en' ? 0 : 1}}>{iconText}</div>
You can pass second prop to useStyles({x,y}), and make condition inside a class

2021-08-12 06:19 UTC, daniel-ilan approved these changes

2021-08-17 15:49 UTC, SejoB requested changes

2021-08-17 15:49 UTC, SejoB commented on src/components/atoms/TooltipMarker.tsx
> +
remove space

2021-08-18 06:38 UTC, SejoB approved these changes

2021-08-18 07:37 UTC, merged