adding rtl theme
hasadna/anyway-newsflash-infographics pull request #740
Opened 2021-08-09 11:17 UTC by EyalIlan

closes #704

2021-08-09 16:04 UTC, SejoB requested changes

2021-08-09 16:04 UTC, SejoB commented on src/App.tsx
> +    // , theme.direction
remove comments

2021-08-09 16:04 UTC, SejoB commented on src/index.tsx
>      <App />
add tab

2021-08-09 16:04 UTC, SejoB commented on src/App.tsx
> +
remove space

2021-08-09 16:04 UTC, SejoB commented on src/App.tsx
> +
remove space

2021-08-09 16:05 UTC, SejoB commented
also don't forget assign yourself to PR

2021-08-10 18:52 UTC, SejoB requested changes

2021-08-10 18:52 UTC, SejoB commented on src/App.tsx
> +  }, [i18n, theme, appDir]);
remove comments

2021-08-11 15:30 UTC, yuvalbl commented on src/App.tsx
> +    // https://material-ui.com/guides/right-to-left/F
remove F

2021-10-06 15:19 UTC, closed without merging