[Feat-757] Add eslint rule for const
hasadna/anyway-newsflash-infographics pull request #758
Opened 2021-08-28 15:45 UTC by MashaPav

2021-08-29 08:54 UTC, daniel-ilan requested changes
The build failed because of the new lint rule. I think you can see what is failing in the "problems" tab in the IDE. 
They need to be fixed before pushing

2021-08-29 08:58 UTC, MashaPav commented
@daniel-ilan Yes, I know, should I go over the variables and change them to const then?

<img width="804" alt="Screenshot 2021-08-29 at 11 57 01" src="https://user-images.githubusercontent.com/61654174/131244817-3b96c58e-e7ea-4ea5-ae26-5bf807438fb2.png">

2021-08-29 09:39 UTC, daniel-ilan commented
Yes, I think

2021-09-01 16:25 UTC, daniel-ilan approved these changes

2021-09-01 17:09 UTC, yuvalbl approved these changes

2021-09-01 17:10 UTC, merged