[feat-851] added street resolution
hasadna/anyway-newsflash-infographics pull request #863
Opened 2022-02-16 18:10 UTC by chenmu10

2022-02-16 18:14 UTC, chenmu10 commented
confirmed it was added to the request: 
![image](https://user-images.githubusercontent.com/13830519/154329352-43bb0ab2-d20b-453e-8f97-3a9ba2e15613.png)

2022-02-23 16:08 UTC, yuvalbl approved these changes

2022-03-02 11:24 UTC, danielsh28 requested changes

2022-03-02 11:24 UTC, danielsh28 commented on src/services/news.data.service.ts
> +  query.push('resolution=suburban_road&resolution=street');
we need to verify that this change does not apply  on prod,  something like : 
```suggestion
 if(!isProd()){ 
  query.push(resolution=street');
}

```

2022-03-30 16:10 UTC, chenmu10 commented
fixed, please approve.

2022-03-30 16:14 UTC, danielsh28 approved these changes

2022-03-30 16:20 UTC, yuvalbl approved these changes

2022-03-30 16:25 UTC, merged