map-size-changed
hasadna/anyway-newsflash-infographics pull request #899
Opened 2022-05-24 08:18 UTC by ItaiOz

Hi Daniel,

I've pushed the changes, waiting for review

2022-05-30 15:08 UTC, ItaiOz commented on src/components/molecules/map/Map.tsx
> +    <MapContainer zoom={zoom} center={center} className={classes.root} style={{ height: '90%', alignSelf: 'end' }}>
Done. inline style got replaced by extra class co compnent

2022-06-09 16:10 UTC, danielsh28 requested changes

2022-06-09 16:10 UTC, danielsh28 commented on src/components/molecules/map/Map.tsx
> +    <MapContainer zoom={zoom} center={center} className={`${classes.root} ${customHeightStyle}`}>
give the map hight or width of 100%

2022-06-09 16:10 UTC, danielsh28 commented on src/components/molecules/widgets/MostSevereAccidentsMapWidget.tsx
> +    height: '95%',
you can change the height here

2022-06-25 08:39 UTC, danielsh28 requested changes

2022-06-25 08:39 UTC, danielsh28 commented on src/components/molecules/LocationMap.tsx
> +const LocationMap: FC<IProps> = ({ items, customHeightStyle }) => {
do we still need `customHeightStyle `? if not remove

2022-07-12 21:06 UTC, merged